var express = require('express');
var bodyParser = require('body-parser');

var app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false })) 

app.use('/:disease',function(req,res){
	var disease = req.params.disease;
	var data={"Apple Scab":{"about":"Apple scab is a disease of Malus trees, such as apple trees, caused by the ascomycete fungus Venturia inaequalis. The best treatment for apple scab begins in the fall, as the tree prepares to go dormant for winter.", "cure" : " Apply a foliar spray of zinc sulfate and urea in the fall. This spray forces the tree to drop its leaves quickly and causes rapid decomposition of the leaf litter."},
			  "Apple Black Rot":{"about":"Black rot is a disease of apples that infects fruit, leaves and bark caused by the fungus Botryosphaeria obtusa. It can also jump to healthy tissue on pear or quince trees, but is typically a secondary fungus of weak or dead tissues in other plants.", "cure": "Treating black rot on apple trees starts with sanitation. Because fungal spores overwinter on fallen leaves, mummified fruits, dead bark and cankers, it’s important to keep all the fallen debris and dead fruit cleaned up and away from the tree."},
			  "Apple Cedar Apple Rust":{"about":"Cedar apple rust (Gymnosporangium juniperi-virginianae) is a fungal disease that requires juniper plants to complete its complicated two year life-cycle. Spores overwinter as a reddish-brown gall on young twigs of various juniper species.", "cure" : "Choose resistant cultivars when available.Rake up and dispose of fallen leaves and other debris from under trees. Remove galls from infected junipers. In some cases, juniper plants should be removed entirely.."},
			  "Apple Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."},
              "Blueberry Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."},
              "Cherry Powdery Mildew":{"about":"Powdery mildew of sweet and sour cherry is caused by Podosphaera clandestina, an obligate biotrophic fungus. Mid- and late-season sweet cherry (Prunus avium) cultivars are commonly affected, rendering them unmarketable due to the covering of white fungal growth on the cherry", "cure" : "The key to managing powdery mildew on the fruit is to keep the disease off of the leaves. Most synthetic fungicides are preventative, not eradicative, so be pro-active about disease prevention. Maintain a consistent program from shuck fall through harvest."},
              "Cherry Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."},
              "Corn Cercospora Gray Leaf Spot":{"about":"Grey leaf spot is a foliar fungal disease that affects maize, also known as corn. There are two fungal pathogens that cause GLS, which are Cercospora zeae-maydis and Cercospora zeina. Symptoms seen on corn include leaf lesions, discoloration, and foliar blight", "cure" : "Repeated application of fungicides will be needed to control this disease effectively during warm, wet periods. Fungicides available for residential use and with the best efficacy for this disease are: Thiophanate-methyl (FRAC group 1), sold as: 1)Bonide Infuse Lawn & Landscape Granules 2)Scotts Lawn Fungus Control (granules)"},
              "Corn Common Rust":{"about":"Common rust pustules appear on upper and lower leaf surfaces. They are typically brown to brownish red, elongated in shape, and scattered on leaf surfaces (Figure 1). Common rust of corn (caused by the fungus Puccinia sorghi) is present at low levels in most Indiana cornfields every year.", "cure" : "If the corn begins to show symptoms of infection, immediately spray with a fungicide. The fungicide is most effective when started at the first sign of infection."},
              "Corn Northern Leaf Blight":{"about":"Northern corn leaf blight is a foliar disease of corn caused by Exserohilum turcicum, the anamorph of the ascomycete Setosphaeria turcica. With its characteristic cigar-shaped lesions, this disease can cause significant yield loss in susceptible corn hybrids.", "cure" : "Growers can manage NLB by selecting resistant hybrids, reducing previous corn residue, timely planting, and in high-risk fields with recent NLB outbreaks, application of fungicides. To determine level of risk, growers are encouraged to routinely scout fields for presence of NLB and other leaf diseases. Scouting is also important to identify any stalk quality problems that often result from leaf diseases."},
              "Corn Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."},
              "Grape Black Rot":{"about":"Grape black rot is a fungal disease caused by an ascomycetous fungus, Guignardia bidwellii, that attacks grape vines during hot and humid weather. Grape black rot affects many grape growers throughout the United States, therefore, it is important to understand the disease life cycle and environmental conditions to best manage the disease. Once infection takes place, different methods are available to control the disease.", "cure" : "Grape black rot is difficult to stop once it has taken hold of growing fruit.Many gardeners would consider this year’s crop a lost cause and work toward preventing a recurrence of disease. Prevention is key when dealing with grape black rot."},
              "Grape Esca":{"about":"Esca is a grape disease of mature grapevines. It is a type of grapevine trunk disease. The fungi Phaeoacremonium aleophilum, Phaeomoniella chlamydospora and Fomitiporia mediterranea are associated with the disease.", "cure" : "As soon as symptoms are determined to be from Esca, not just the cordons, but the entire plant must be removed. The longer this is put off, the greater the possibility that removal will be ineffective. The most current approach in the last several years has been to fight Esca naturally with biological enemies."},
              "Grape Leaf Blight":{"about":"The fungus is an obligate pathogen which can attack all green parts of the vine. Symptoms of this disease are frequently confused with those of powdery mildew. Infected leaves develop pale yellow-green lesions which gradually turn brown. Severely infected leaves often drop prematurely.", "cure" : "Baking Soda for Fungus on Grapevines. Baking soda, bicarbonate of soda, is derived from a mineral called trona. The many uses of baking soda stem, in part, from its amphoteric properties -- the ability to neutralize both acids and bases. The pH-altering effects of baking soda control powdery mildew fungi, not killing the spores, but interrupting the life cycle through inhibition of germination."},
              "Grape Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."},
              "Orange Haunglongbing":{"about":"It is a disease of citrus caused by a vector-transmitted pathogen. The causative agents are motile bacteria, Candidatus Liberibacter spp. The disease is vectored and transmitted by the Asian citrus psyllid, Diaphorina citri, and the African citrus psyllid, Trioza erytreae, also known as the two-spotted citrus psyllid. It has also been shown to be graft-transmissible", "cure" : " Cultural methods include antibacterial management, sanitation, removal of infected plants, frequent scouting, and most importantly, crisis declaration. Tracking the disease will help prevent further infection in other affected areas and help mitigate more local infections if detected early enough."},
              "Peach Bacterial Spot":{"about":"Bacterial spot is a difficult disease to control when environmental conditions favor pathogen spread. As with all bacterial plant diseases, there are relatively few bactericide chemicals available for use. Compounds available for use on peach and nectarine for bacterial spot include copper, oxytetracycline.", "cure" : "Oxytetracycline is generally considered the most effective compound and the least prone to phytotoxicity problems (damage to plant tissue), but also perhaps most likely to lose effectiveness with the appearance of bacterial strains with resistance."},
              "Peach Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."},
              "Bell Pepper Bacterial Spot":{"about":"Bacterial spot is caused by the bacterium Xanthomonas campestris pv. vesicatoria. The same bacterial disease affects tomato. Like most bacterial diseases, bacterial spot is difficult to control when frequent rains and moist conditions prevail.", "cure" : "The first strategy to use for controlling any disease is to eliminate or reduce the amount of the pathogen available to initiate disease. An important source of the bacterium that causes BLS in pepper is infested seed. Therefore, the use of disease-free seed and transplants are some of the most important BLS management practices. Infested crop debris and infected weeds are additional sources of the pathogen and must also be managed in an effective BLS control program."},
              "Bell Pepper Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."},
              "Potato Early Blight":{"about":"Symptoms of early blight occur on fruit, stem and foliage of tomatoes and stem, foliage and tubers of potatoes.  Initial symptoms on leaves appear as small 1-2 mm black or brown lesions and under conducive environmental conditions the lesions will enlarge and are often surrounded by a yellow halo.", "cure" : "Fungicides with  protectant and curative properties are registered for use against early blight on tomato and potato (Figure 10). The cheaper protectant fungicides such as mancozeb and chlorothalonil are the foundation of most early blight management programs. These fungicides must be reapplied every 7-10 days to provide protection of new growth as well as to counter the effects of weathering which progressively removes the chemical from the leaf surface. Advantages of these types of products include their reliable efficacy and multi-site mode of action, which reduces the risk of resistant isolates developing in the pathogen population."},
              "Potato Late Blight":{"about":"Ate blight of potato is identified by black/brown lesions on leaves and stems that may be small at first and appear water-soaked or have chlorotic borders, but soon expand rapidly and become necrotic. In humid conditions, Phytophthora infestans produces sporangia and sporangiophores on the surface of infected tissue. This sporulation results in a visible white growth at the leading edge of lesions on abaxial (lower) surfaces of leaves.", "cure" : "Fungicide applications (Figures 1, 28) are an important means of late blight management, particularly in humid areas. Contact fungicides are effective and have not resulted in pathogen resistance after many years of use. They coat the leaves to prevent infection, but cannot stop infections once they occur. Therefore, they must be applied before plants are exposed to spores. Systemic fungicides can offer some post-infection control."},
              "Potato Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."},
              "Raspberry Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."},
              "Soybean Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."},
              "Squash Powdery Mildew":{"about":"Conidia (spores) are rapidly produced in the powdery mycelium and any wind or air movement carries them to adjacent plants and leaves as well as off to plants situated even farther away. ... Also, powdery mildew in cucurbits is spread because the disease overwinters and is spread to successive generations of squash.", "cure" : "Spray on plants every one to two weeks. Potassium bicarbonate– Similar to baking soda, this has the unique advantage of actually eliminating powdery mildew once it's there. Potassium bicarbonate is a contact fungicide which kills the powdery mildew spores quickly. In addition, it's approved for use in organic growing."},
              "Strawberry Leaf Scorch":{"about":"Leaf Scorch is the most common leaf disease in matted row systems in North Carolina but rarely occurs in annual production systems. The pathogen can survive and cause disease at a wide range of temperatures, and has been reported to cause disease year-round on perennial crops", "cure" : "The best way to treat this disease is to alter watering practices and allow for dryer conditions. If that isn't possible, you can treat your strawberries with organic fungicides like Captan 50 WP and Copper compounds."},
              "Strawberry Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."},
              "Tomato Bacterial Spot":{"about":"Three bacterial diseases are common in Ontario tomato fields: bacterial spot, caused by Xanthomonas campestris pv. vesicatoria; bacterial speck, caused by Pseudomonas syringae pv. tomato; and bacterial canker, caused by Clavibacter michiganensis subsp. michiganensis.", "cure" : "Hot Water Treatment :- Place the seed in a loosely woven cotton bag (such as cheesecloth). Leave lots of room in the bag for the seed to move around. Prewarm the seed for 10 min in 37°C (100°F) water. Place pre-warmed seed in hot water at 50°C (122°F) for 25 min, monitoring the temperature constantly. "},
              "Tomato Early Blight":{"about":"Early blight is one of the most common tomato diseases, occurring nearly every season wherever tomatoes are grown. It affects leaves, fruits and stems and can be severely yield limiting when susceptible cultivars are used and weather is favorable.", "cure" : "There are many resistant tomato cultivars available, often designated with an EB in seed catalogs. There is also an extensive list of resistant cultivars on Cornell University's vegetable pathology website. Resistant varieties are not immune to early blight. Rather moderate levels of resistance to either leaf infection, stem infection or both are present."},
              "Tomato Late Blight":{"about":"The fungus, (Phytophthora infestans), that causes late blight is aptly named: phytophthora in Latin means plant destroyer. Infected plant tissue dies. Outbreaks spread quickly under favorable conditions because the pathogen can produce huge numbers of wind-dispersed spores. Once a plant is infected, it must be destroyed. ", "cure" : "1) Plant resistant cultivars when available. 2) Remove volunteers from the garden prior to planting and space plants far enough apart to allow for plenty of air circulation. 3) Water in the early morning hours, or use soaker hoses, to give plants time to dry out during the day — avoid overhead irrigation. 4) Destroy all tomato and potato debris after harvest (see Fall Garden Cleanup)."},
              "Tomato Leaf Mold":{"about":"The tomato leaf mold fungus is a specific pathogen of tomato plant Lycopersicon, this pathogen has restricted host range (host specific pathogen) that only infects tomatoes, mainly greenhouses.", "cure" : "he least but not the less important management is the chemical control that ensure good control of the disease. The chemical control is basically spraying fungicide as soon as the symptoms are evident. Compounds registered for using are: chlorothalonil, maneb, mancozeb and copper."},
              "Tomato Septoria Leaf Spot":{"about":"Septoria leaf spot is caused by a fungus, Septoria lycopersici. It is one of the most destructive diseases of tomato foliage and is particularly severe in areas where wet, humid weather persists for extended periods. Septoria leaf spot usually appears on the lower leaves after the first fruit sets.", "cure" : "1. Remove diseased leaves. 2) Use crop rotation 3) Use fungicidal sprays."},
              "Tomato Spider Mites":{"about":"Spider mites (Tetranychus spp.) can ruin a tomato (Lycopersicon esculentum) garden when they colonize the undersides of leaves and suck plant juices. Tiny arachnids, spider mites are in the same family as spiders and ticks and are one of the major pest problems of tomato plants.", "cure" : "Regular forceful spraying of tomato plants, with care to reach the undersides of leaves, helps prevent spider mites from colonizing on your plants, according to the University of California Statewide Integrated Pest Management Program."},
              "Tomato Target Spot":{"about":"Target spot is frequently misdiagnosed in its early stages as symptoms are difficult to recognize and can be confused with bacterial spot and early blight. The name derives from the bull's-eye appearance that is often displayed in lesions caused by the disease. ... On tomato fruit, lesions are more distinct", "cure" : "Target spot tomato treatment requires a multi-pronged approach. The following tips for treating target spot on tomatoes should help: ... Rotate crops and don't plant tomatoes in areas where other disease-prone plants have been located in the past year – primarily eggplant, peppers, potatoes or, of course – tomatoes."},
              "Tomato Yellow Leaf Curl Virus":{"about":"Tomato yellow leaf curl virus is a DNA virus from the genus Begomovirus and the family Geminiviridae. TYLCV causes the most destructive disease of tomato, and it can be found in tropical and subtropical regions causing severe economic losses.", "cure" : "Use a neonicotinoid insecticide, such as dinotefuran (Venom) imidacloprid (AdmirePro, Alias, Nuprid, Widow, and others) or thiamethoxam (Platinum), as a soil application or through the drip irrigation system at transplanting of tomatoes or peppers."},
              "Tomato Mosaic Virus":{"about":"Tomato mosaic virus (ToMV) is a plant pathogenic virus. It is found worldwide and affects tomatoes and many other plants.", "cure" : "The only treatment is prevention. No chemical products are available to cure or protect plants. The best factor in controlling and reducing infection is to practice sanitation. Remove any infected plants, including the roots. Remove Also, discard any plants near those affected."},
              "Tomato Healthy":{"about":"Don't panic your plant is free from all diseases.", "cure" : "No treatment required."}

			  };
			  var result = data[disease];
	res.send( { disease: disease, value : result } );
})
app.use('/*',function(req,res){
	res.send('404 Error');
})
var port = process.env.PORT || 3000
app.listen(port, function() {
    console.log("App is running on port " + port);
});